### ISSUE TITLE
Optimize model serialization size

### ISSUE THREAD

**Issue by dacorvo** [aws-neuron/transformers-neuronx#17]
When instantiating a model that has already been compiled, one can simply point to the serialized compiled artifacts to avoid recompiling the model.

However, before reaching that point, we must still instantiate the model from the original checkpoint.

This means that unless I am mistaken, to completely serialize the model, we need to store the weights twice: once in the checkpoint and once in the compiled artifacts.

Would it be possible to instantiate a pre-compiled model without the original checkpoint, and divide the storage requirements by two (or even more if the compiled artifacts use a lower precision) ?

**Comment by mrnikwaws** [comment]
Hi @dacorvo,

First up the compiled artifacts (i.e. the NEFF files in the compiler cache) don't include weights for the transformers-neuronx models.  

We do create a 'split' version of the checkpoint, (the split is called in user code) that we use to gradually load weights in without exhausting host memory on a checkpoint load.  

It is possible to delete the native checkpoint file and keep the split version if you want to save space, since only the latter is required to load a checkpoint.

**Comment by dacorvo** [comment]
> Hi @dacorvo,
> 
> First up the compiled artifacts (i.e. the NEFF files in the compiler cache) don't include weights for the transformers-neuronx models.

My bad: I got confused because I save everything under a single directory, and the split checkpoint is quite bigger than the original one (for GPT2 it is 623 M versus 475 M), which leads to an overall size increase. The compiled artifacts are however only a few kilobytes.

> We do create a 'split' version of the checkpoint, (the split is called in user code) that we use to gradually load weights in without exhausting host memory on a checkpoint load.
> 
> It is possible to delete the native checkpoint file and keep the split version if you want to save space, since only the latter is required to load a checkpoint.

Yes , I am doing that already.

Anyway, thank you for your answer. Closing the issue as there isn't any further optimization required.

**Comment by dacorvo** [comment]
Closing the issue as there isn't any further optimization required.
