### ISSUE TITLE
neuronx-cc --target

### ISSUE THREAD

**Issue by sheenobu** [aws-neuron/transformers-neuronx#31]
I noticed /usr/local/bin/neuronx-cc is always called with --target=trn1 even on my inf2 machines.

https://github.com/aws-neuron/transformers-neuronx/blob/main/src/transformers_neuronx/compiler.py#L80-L81

I'm evaluating non-GPU machines. Will this have any speed or quality effects when evaluating inf2 machines?

**Comment by jluntamazon** [comment]
Hello,

Currently there is no difference between the `inf2`/`trn1` compiler switch since both instance types use the same underlying NeuronCore architecture.

Architecture Reference: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/index.html

This switch may enable instance-specific optimizations in the *future*, but you should not see any negative effects by using trn1 as the default *today*.

**Comment by sheenobu** [comment]
cool, thanks.
